from enum import Enum


class MissionState(str, Enum):
    IDLE = 'IDLE'
    ACCEPTED = 'ACCEPTED'
    GO_TO_PICKUP = 'GO_TO_PICKUP'
    WAIT_FOR_LOADING = 'WAIT_FOR_LOADING'
    CARGO_LOADED = 'CARGO_LOADED'
    GO_TO_PRE_DOCK = 'GO_TO_PRE_DOCK'
    DOCKING = 'DOCKING'
    DOCKED = 'DOCKED'
    UNLOADING = 'UNLOADING'
    COMPLETED = 'COMPLETED'
    NEXT_MISSION = 'NEXT_MISSION'
