<?xml version="1.0"?>
<package format="3">
  <name>system_tests</name>
  <version>0.1.0</version>
  <description>Integration tests for perception and navigation pipelines.</description>
  <maintainer email="nguyendangtuyen062004@gmail.com">Nguyen Dang Tuyen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>fusion_bringup</exec_depend>
  <exec_depend>navigation_bringup</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_index_python</test_depend>
  <test_depend>fusion_interfaces</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing_ros</test_depend>
  <test_depend>perception_core</test_depend>
  <test_depend>navigation_bringup</test_depend>
  <test_depend>navigation_bridge</test_depend>
  <test_depend>openamrobot_description</test_depend>
  <test_depend>warehouse_mission_manager</test_depend>
  <test_depend>warehouse_simulation</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>sensor_msgs</test_depend>
  <test_depend>tf2_ros</test_depend>
  <test_depend>std_srvs</test_depend>
  <test_depend>visualization_msgs</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
